//! Render the catalogue as Rust source.

use std::collections::{BTreeMap, BTreeSet};

use crate::engine_tables::PathEntry;
use crate::kinds::ParamForm;
use crate::signatures::Implementation;

pub struct Catalogue {
    pub revision: String,
    pub functions: Vec<CatalogueEntry>,
    pub constants: Vec<String>,
    pub renames: Vec<(String, String)>,
    pub not_callable: Vec<String>,
    pub namespaces: BTreeSet<String>,
}

pub struct CatalogueEntry {
    pub name: String,
    pub params: Vec<crate::kinds::Param>,
    pub is_async: bool,
    /// True when the name is in `PATHS` but no dispatch arm implements it in
    /// call form, so the parser accepts it and the engine then refuses it.
    pub not_callable: bool,
    /// True when the generator read this function's implementation.
    ///
    /// Load-bearing for the argument checks. Without it an unreadable signature
    /// and a genuinely zero-argument function are both `params: &[]`, and the
    /// checker would report "expects 0 arguments" for every call to the former.
    pub signature_known: bool,
}

/// Namespaces whose leading arguments the runtime supplies, so the Rust
/// signature is wider than what an author writes.
///
/// `api::` holds middleware. `api::timeout` reads
/// `(req, next, timeout): (Value, Box<Closure>, Duration)`, but the API runtime
/// supplies `req` and `next`; the author writes `api::timeout(30s)`. Nothing in
/// the types marks the first two as injected — `Box<Closure>` is an ordinary
/// author-supplied argument in `array::map` and `value::chain` — so the
/// convention cannot be detected, only recorded.
///
/// These are reported with an unknown signature, which means silence. Checking
/// them would report a wrong count on every valid middleware clause; SurrealDB's
/// own `language-tests/tests/api/` corpus proved it.
const RUNTIME_SUPPLIED_NAMESPACES: &[&str] = &["api::"];

fn has_runtime_supplied_arguments(name: &str) -> bool {
    RUNTIME_SUPPLIED_NAMESPACES
        .iter()
        .any(|namespace| name.starts_with(namespace))
}

/// Join the engine's three tables into one catalogue.
pub fn build(
    paths: &[PathEntry],
    dispatch: &BTreeMap<String, String>,
    implementations: &BTreeMap<String, Implementation>,
    revision: String,
    namespaces: BTreeSet<String>,
) -> Catalogue {
    let mut functions = Vec::new();
    let mut constants = Vec::new();
    let mut renames = Vec::new();
    let mut not_callable = Vec::new();

    for entry in paths {
        if let Some(previous) = &entry.previous_name {
            renames.push((previous.clone(), entry.name.clone()));
        }
        if !entry.is_function {
            constants.push(entry.name.clone());
            continue;
        }

        let implementation = dispatch
            .get(&entry.name)
            .and_then(|path| implementations.get(path));
        let missing = !dispatch.contains_key(&entry.name);
        if missing {
            not_callable.push(entry.name.clone());
        }
        let runtime_supplied = has_runtime_supplied_arguments(&entry.name);

        functions.push(CatalogueEntry {
            name: entry.name.clone(),
            params: if runtime_supplied {
                Vec::new()
            } else {
                implementation
                    .map(|found| found.params.clone())
                    .unwrap_or_default()
            },
            is_async: implementation.is_some_and(|found| found.is_async),
            not_callable: missing,
            signature_known: implementation.is_some() && !runtime_supplied,
        });
    }

    renames.sort();
    renames.dedup();
    Catalogue {
        revision,
        functions,
        constants,
        renames,
        not_callable,
        namespaces,
    }
}

pub fn render(catalogue: &Catalogue) -> String {
    let mut out = String::new();

    out.push_str(&format!(
        "//! The SurrealDB builtin function catalogue.\n\
         //!\n\
         //! @generated by `cargo xtask generate-builtins` — do not edit by hand.\n\
         //! Generated from the SurrealDB checkout at revision `{revision}`, out of\n\
         //! `syn/parser/builtin.rs` (the names), `fnc/mod.rs` (the dispatch tables) and\n\
         //! the `pub fn` signatures under `fnc/`.\n\
         //!\n\
         //! A parameter the generator could not read is typed `any`, which silences the\n\
         //! argument check for that position. That is deliberate: a wrong type here would\n\
         //! invent a diagnostic against valid SurrealQL.\n\
         \n\
         use crate::grammar::{{GeneratedFunction, GeneratedParam, ParamForm}};\n\
         \n\
         /// The SurrealDB revision this catalogue was generated from.\n\
         pub const SURREALDB_REVISION: &str = \"{revision}\";\n\n",
        revision = catalogue.revision
    ));

    out.push_str(&format!(
        "/// Every function name the SurrealDB parser accepts, with the argument types\n\
         /// its implementation declares. {count} entries.\n\
         pub const GENERATED_FUNCTIONS: &[GeneratedFunction] = &[\n",
        count = catalogue.functions.len()
    ));
    for entry in &catalogue.functions {
        out.push_str(&render_entry(entry));
    }
    out.push_str("];\n\n");

    out.push_str(&format!(
        "/// The namespace prefixes that really exist, derived from the names above.\n\
         /// {count} entries.\n\
         pub const GENERATED_NAMESPACES: &[&str] = &[\n",
        count = catalogue.namespaces.len()
    ));
    for namespace in &catalogue.namespaces {
        out.push_str(&format!("    \"{namespace}\",\n"));
    }
    out.push_str("];\n\n");

    out.push_str(&format!(
        "/// Constants such as `math::PI`. They take no arguments and are not called.\n\
         /// {count} entries.\n\
         pub const GENERATED_CONSTANTS: &[&str] = &[\n",
        count = catalogue.constants.len()
    ));
    for constant in &catalogue.constants {
        out.push_str(&format!("    \"{constant}\",\n"));
    }
    out.push_str("];\n\n");

    out.push_str(&format!(
        "/// Renamed functions, as `(previous spelling, current spelling)`. The engine\n\
         /// keeps these to suggest a replacement, so they make a quick fix. {count} pairs.\n\
         pub const RENAMED_FUNCTIONS: &[(&str, &str)] = &[\n",
        count = catalogue.renames.len()
    ));
    for (previous, current) in &catalogue.renames {
        out.push_str(&format!("    (\"{previous}\", \"{current}\"),\n"));
    }
    out.push_str("];\n\n");

    out.push_str(&format!(
        "/// Names the parser accepts that no dispatch arm implements in call form. A\n\
         /// query using one parses and then fails at run time. {count} entries.\n\
         pub const PARSES_BUT_NOT_CALLABLE: &[&str] = &[\n",
        count = catalogue.not_callable.len()
    ));
    for name in &catalogue.not_callable {
        out.push_str(&format!("    \"{name}\",\n"));
    }
    out.push_str("];\n");

    out
}

fn render_entry(entry: &CatalogueEntry) -> String {
    let mut out = String::new();
    out.push_str("    GeneratedFunction {\n");
    out.push_str(&format!("        name: \"{}\",\n", entry.name));
    if entry.params.is_empty() {
        out.push_str("        params: &[],\n");
    } else {
        out.push_str("        params: &[\n");
        for param in &entry.params {
            out.push_str(&format!(
                "            GeneratedParam {{ name: \"{}\", ty: \"{}\", form: ParamForm::{} }},\n",
                param.name,
                param.ty,
                form_name(param.form)
            ));
        }
        out.push_str("        ],\n");
    }
    out.push_str(&format!("        is_async: {},\n", entry.is_async));
    out.push_str(&format!("        not_callable: {},\n", entry.not_callable));
    out.push_str(&format!(
        "        signature_known: {},\n",
        entry.signature_known
    ));
    out.push_str("    },\n");
    out
}

fn form_name(form: ParamForm) -> &'static str {
    match form {
        ParamForm::Required => "Required",
        ParamForm::Optional => "Optional",
        ParamForm::Variadic => "Variadic",
    }
}
